name: Read Issue Body

on:
  issues:
    types: [opened, edited]

jobs:
  read-issue-body:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get issue body
      id: get_issue
      uses: actions/github-script@v7
      with:
        script: |
          const issue = await github.rest.issues.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number
          });
          core.setOutput("body", issue.data.body);

    - name: Print issue body
      run: echo "${{ steps.get_issue.outputs.body }}"

    - name: Call Azure OpenAI API
      run: |
        curl -X POST "https://malmi-maeexi1k-eastus2.cognitiveservices.azure.com/openai/deployments/o4-mini/chat/completions?api-version=2024-12-01-preview" \
          -H "Content-Type: application/json" \
          -H "api-key: ${{ secrets.AZURE_OPENAI_API_KEY }}" \
          -d '{
            "messages": [{"role": "user", "content": "Implement this user story: ${{ steps.get_issue.outputs.body }}"}],
            "temperature": 0.7,
            "max_tokens": 100
          }'
    
    - name: LS
      run: |
        ls -la